import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Camera, Mail, MapPin, MessageCircle, Phone, Send, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { defaultSiteContact, SiteContact } from "@/lib/site-contact";

export const metadata:Metadata={title:"Aloqa",description:"MAKTAB X jamoasi bilan bog‘laning."};
export default async function ContactPage(){
 let contact=defaultSiteContact;
 try{const db=await createClient();const {data}=await db.from("site_contact").select("id,title,body,phone,telegram_handle,instagram_handle,image_url").eq("id",1).maybeSingle();if(data)contact={...defaultSiteContact,...data} as SiteContact}catch{/* Use the ready-made public contact card until the contact migration is applied. */}
 const phoneHref=`tel:${contact.phone.replace(/[^+\d]/g,"")}`;const telegram=contact.telegram_handle.replace(/^@/,"").trim();const instagram=contact.instagram_handle.replace(/^@/,"").trim();
 return <main className="contact-page"><header className="contact-nav"><Link href="/"><Image src="/assets/maktabx-logo.svg" alt="MAKTAB X" width={184} height={44}/></Link><div><Link href="/welcome">Platforma bilan tanishish</Link><Link className="contact-signin" href="/login">Hisobga kirish <ArrowRight size={14}/></Link></div></header><section className="contact-hero"><div className="contact-copy"><Link className="contact-back" href="/"><ArrowLeft size={14}/> Bosh sahifa</Link><div className="contact-kicker"><Sparkles size={14}/> BIZ SIZ BILAN BOG‘LANISHGA TAYYORMIZ</div><h1>{contact.title}</h1><p>{contact.body}</p><div className="contact-availability"><span className="contact-live-dot"/>MAKTAB X jamoasi sizga yordam beradi</div><div className="contact-actions"><a className="contact-method call" href={phoneHref}><span><Phone size={19}/></span><div><small>TELEFON ORQALI</small><b>{contact.phone}</b><em>Qo‘ng‘iroq qilish</em></div><ArrowRight size={16}/></a><a className="contact-method telegram" href={`https://t.me/${telegram}`} target="_blank" rel="noreferrer"><span><Send size={19}/></span><div><small>TELEGRAM</small><b>@{telegram}</b><em>Telegram’da yozish</em></div><ArrowRight size={16}/></a><a className="contact-method instagram" href={`https://instagram.com/${instagram}`} target="_blank" rel="noreferrer"><span><Camera size={19}/></span><div><small>INSTAGRAM</small><b>@{instagram}</b><em>Sahifani ochish</em></div><ArrowRight size={16}/></a></div><div className="contact-safety"><MapPin size={15}/><span>O‘zbekiston maktablari uchun ta’lim platformasi</span></div></div><div className="contact-art"><div className="contact-art-orbit orbit-a"/><div className="contact-art-orbit orbit-b"/>{contact.image_url?<img src={contact.image_url} alt="MAKTAB X roboti va Bilimcha aloqa sahifasida"/>:<Image src="/assets/contact-hero.png" alt="MAKTAB X roboti va Bilimcha" width={1536} height={1024} priority/>}<div className="contact-art-note"><span><MessageCircle size={16}/></span><div><b>Savolingiz bormi?</b><small>O‘zimizga qulay aloqa usulini tanlang</small></div></div><div className="contact-sparkle sparkle-a">✦</div><div className="contact-sparkle sparkle-b">✧</div></div></section><footer className="contact-footer"><Link href="/"><Image src="/assets/maktabx-logo.svg" alt="MAKTAB X" width={146} height={33}/></Link><span>© {new Date().getFullYear()} MAKTAB X · Bilim hamma uchun</span><Link href="mailto:yordam@maktabx.uz"><Mail size={14}/> Email orqali yozish</Link></footer></main>
}
