import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { roleLabels } from "@/lib/roles";
import { InviteForm } from "../invitations/invite-form";
import { ArrowLeft,Inbox,Plus,ShieldCheck } from "lucide-react";
import { InteractiveHub } from "@/components/interactive-hub";
import { SchoolMessenger } from "@/components/school-messenger";
import { SchoolProvisionForm } from "@/components/school-provision-form";
import { ClassLeaderManager } from "@/components/class-leader-manager";
import { TeacherAssignmentManager } from "@/components/teacher-assignment-manager";

const config:Record<string,{title:string;description:string;table?:string;columns?:[string,string][];filter?:string}>={
 invitations:{title:"Rollar va takliflar",description:"Maktab a’zolarini xavfsiz taklif qilish"},
 grades:{title:"Baholar",description:"Fanlar kesimida o‘quv natijalari",table:"grades",columns:[["assessed_at","Sana"],["subject_id","Fan ID"],["score","Natija"],["feedback","Izoh"]],filter:"student"},
 homework:{title:"Uy vazifalari",description:"Topshiriqlar, muddatlar va topshirilgan ishlar",table:"homework",columns:[["title","Topshiriq"],["subject_id","Fan ID"],["due_at","Topshirish muddati"],["instructions","Ko‘rsatma"]]},
 attendance:{title:"Davomat",description:"Darslarda qatnashish qaydlari",table:"attendance",columns:[["recorded_at","Sana"],["status","Holat"],["note","Izoh"]],filter:"student"},
 schedule:{title:"Dars jadvali",description:"Haftalik dars vaqtlari",table:"lessons",columns:[["weekday","Hafta kuni"],["starts_at","Boshlanishi"],["ends_at","Tugashi"],["room","Xona"]]},
 announcements:{title:"E’lonlar",description:"Maktab va sinf yangiliklari",table:"announcements",columns:[["title","Sarlavha"],["body","Matn"],["published_at","E’lon qilingan"]]},
 classes:{title:"Sinflar",description:"Maktab sinflari ro‘yxati",table:"classes",columns:[["name","Sinf"],["grade_level","Bosqich"],["room","Xona"],["academic_year","O‘quv yili"]]},
 students:{title:"O‘quvchilar",description:"Sizga ruxsat etilgan o‘quvchilar",table:"class_members",columns:[["student_id","O‘quvchi ID"],["class_id","Sinf ID"],["joined_at","Qo‘shilgan"]]},
 teachers:{title:"O‘qituvchilar",description:"Maktab o‘qituvchilari",table:"teacher_assignments",columns:[["teacher_id","O‘qituvchi ID"],["class_id","Sinf ID"],["subject_id","Fan ID"]]},
 subjects:{title:"Fanlar",description:"O‘quv fanlari katalogi",table:"subjects",columns:[["name","Fan nomi"]]},
 rewards:{title:"X Coin va mukofotlar",description:"Maktab tomonidan tasdiqlangan mukofotlar",table:"rewards",columns:[["name","Mukofot"],["description","Tavsif"],["cost","Qiymat"]]},
 notifications:{title:"Bildirishnomalar",description:"Hisobingizga yuborilgan xabarlar",table:"notifications",columns:[["title","Sarlavha"],["body","Xabar"],["created_at","Sana"]]},
 children:{title:"Farzandlarim",description:"Ota-ona bilan tasdiqlangan farzandlar",table:"parent_student_links",columns:[["student_id","O‘quvchi ID"],["relationship","Qarindoshlik"]]},
 messages:{title:"Xabarlar",description:"Maktab hamjamiyati bilan yozishmalar"},
 reports:{title:"Hisobotlar",description:"Maktab faoliyati bo‘yicha ruxsatli jamlanma"},audit:{title:"Audit jurnali",description:"Ma’muriy amallar tarixi",table:"audit_logs",columns:[["action","Amal"],["entity","Obyekt"],["created_at","Sana"]]},
 users:{title:"Foydalanuvchilar",description:"Maktabdagi faollashtirilgan hisoblar",table:"school_memberships",columns:[["user_id","Hisob ID"],["role","Rol"],["status","Holat"]]},
 library:{title:"Maktab kutubxonasi",description:"Kitoblar va mutolaa"}, lessons:{title:"O‘yinli darslar",description:"Qisqa mavzular va topshiriqlar"},
 community:{title:"Maktab hamjamiyati",description:"Maktab ichidagi postlar va obunalar"}, kitchen:{title:"Oshpaz paneli",description:"CoinShop QR tekshiruvlari"},
 schools:{title:"Maktablar",description:"Tizimga biriktirilgan maktablar",table:"schools",columns:[["name","Nomi"],["slug","Manzil kodi"],["region","Hudud"]]},
 settings:{title:"Sozlamalar",description:"Maktab ish joyi va hisob sozlamalari"},leaderboard:{title:"Reyting",description:"Maktabdagi o‘quv yutuqlari",table:"coin_accounts",columns:[["student_id","O‘quvchi ID"],["balance","X Coin"]]},cafeteria:{title:"Oshxona",description:"Maktab oshxonasi mahsulotlari",table:"cafeteria_items",columns:[["name","Mahsulot"],["description","Tavsif"],["price","Narx"]]},tutor:{title:"AI Ustoz",description:"O‘quv mavzularini tushuntiruvchi shaxsiy yordamchi"}
};
export default async function SectionPage({params}:{params:Promise<{section:string}>}){
 const {section}=await params;const sectionConfig=config[section];if(!sectionConfig)notFound();
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return null;
 const {data:isSuperAdmin}=await db.rpc("is_platform_super_admin");
 const {data:m}=isSuperAdmin?{data:{school_id:"",role:"super_admin"}}:await db.from("school_memberships").select("school_id,role").eq("user_id",user.id).eq("status","active").limit(1).single();
 if(!m)return null;
 if(m.role==="super_admin"&&!["schools","users","audit"].includes(section))notFound();
 if(m.role==="super_admin"&&!["schools","users","audit"].includes(section))notFound();
 if(section==="kitchen"&&m.role!=="cook")notFound();
 if(section==="messages")return <SchoolMessenger schoolId={m.school_id} userId={user.id} name={user.user_metadata?.full_name||user.email||"Foydalanuvchi"}/>;
 if(section==="rewards"&&!( ["admin","director","student","cook"].includes(m.role)))notFound();
 if(["library","lessons","community","rewards","kitchen","cafeteria"].includes(section)){
  return <InteractiveHub section={section as "library"|"lessons"|"community"|"rewards"|"kitchen"|"cafeteria"} schoolId={m.school_id} school="Maktab" role={m.role as import("@/lib/roles").AppRole} userId={user.id} name={user.user_metadata?.full_name||user.email||"Foydalanuvchi"}/>;
 }
 if(["invitations"].includes(section)&&!(["admin","director"].includes(m.role)))notFound();
 if(section==="schools"&&isSuperAdmin){type SchoolRow={id:string;name:string;slug:string;school_number:string|null;province:string|null;district:string|null};const {data:schools}=await db.from("schools").select("id,name,slug,school_number,province,district,enabled").order("name").limit(200);const schoolRows=(schools||[]) as SchoolRow[];return <><div className="page-title-row"><div><h1>Maktablarni platformaga ulash</h1><p>Respublika, viloyat, tuman va maktab darajasida boshqaruvni boshlang.</p></div><span className="result-count">{schoolRows.length} ta maktab</span></div><section className="panel form-panel"><div className="panel-heading"><div><h3>Yangi maktab va birinchi admin</h3><p>Maktab yozuvi va admin taklifi bitta amalda bazaga tushadi.</p></div><span className="secure-pill"><ShieldCheck size={14}/> Super-admin</span></div><SchoolProvisionForm/></section><section className="panel data-panel"><div className="panel-heading"><div><h3>Ulangan maktablar</h3><p>Hudud va maktab raqami bilan.</p></div></div><div className="table-wrap"><table><thead><tr><th>Maktab</th><th>Raqam</th><th>Viloyat</th><th>Tuman</th><th>Kod</th></tr></thead><tbody>{schoolRows.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.school_number||"—"}</td><td>{s.province||"—"}</td><td>{s.district||"—"}</td><td>{s.slug}</td></tr>)}</tbody></table></div></section></>}
 if(section==="classes"){type Profile={id:string;full_name:string|null};type RosterMember={student_id:string;profiles:Profile|null};type ClassRow={id:string;name:string;grade_level:number;room:string|null;academic_year:string;class_leader_id:string|null;leader:Profile|null;homeroom_teacher_id:string|null;homeroom_teacher:Profile|null;class_members:RosterMember[]};const [{data:classes},{data:studentRows}]=await Promise.all([db.from("classes").select("id,name,grade_level,room,academic_year,class_leader_id,leader:mx_profiles!classes_class_leader_id_fkey(id,full_name),homeroom_teacher_id,homeroom_teacher:mx_profiles!classes_homeroom_teacher_id_fkey(id,full_name),class_members(student_id,profiles:mx_profiles(id,full_name))").eq("school_id",m.school_id).order("grade_level"),db.from("school_memberships").select("user_id,mx_profiles(full_name)").eq("school_id",m.school_id).eq("role","student").eq("status","active")]);const roster=((classes||[]) as unknown as ClassRow[]).map(c=>({id:c.id,name:c.name,grade_level:c.grade_level,room:c.room,academic_year:c.academic_year,class_leader_id:c.class_leader_id,class_leader_name:c.leader?.full_name||null,homeroom_teacher_id:c.homeroom_teacher_id,homeroom_teacher_name:c.homeroom_teacher?.full_name||null,students:(c.class_members||[]).map(x=>({id:x.student_id,name:x.profiles?.full_name||x.student_id.slice(0,8)}))}));type StudentRow={user_id:string;mx_profiles:Profile|null};const candidates=((studentRows||[]) as unknown as StudentRow[]).map(s=>({id:s.user_id,name:s.mx_profiles?.full_name||s.user_id.slice(0,8)}));return <><div className="page-title-row"><div><h1>Sinflar va sinf sardorlari</h1><p>Sinf rahbari maktabdagi faol o‘quvchini sinfga qo‘shadi va sardorni belgilaydi.</p></div></div><section className="panel data-panel"><ClassLeaderManager classes={roster} schoolId={m.school_id} candidates={candidates}/></section></>}
 if(section==="teachers"){type MemberRow={user_id:string;mx_profiles:{full_name:string;email:string|null}|null};type ClassChoice={id:string;name:string};type SubjectChoice={id:string;name:string};const [{data:teacherRows},{data:classRows},{data:subjectRows}]=await Promise.all([db.from("school_memberships").select("user_id,mx_profiles(full_name,email)").eq("school_id",m.school_id).eq("role","teacher").eq("status","active"),db.from("classes").select("id,name").eq("school_id",m.school_id).order("grade_level"),db.from("subjects").select("id,name").eq("school_id",m.school_id).order("name")]);const teachers=((teacherRows||[]) as unknown as MemberRow[]).map(t=>({id:t.user_id,name:t.mx_profiles?.full_name||t.user_id.slice(0,8),email:t.mx_profiles?.email||""}));return <><div className="page-title-row"><div><h1>O‘qituvchilar va taqsimot</h1><p>Direktor fan o‘qituvchilarini va sinf rahbarlarini tayinlaydi.</p></div><span className="result-count">{teachers.length} faol o‘qituvchi</span></div><section className="panel data-panel"><TeacherAssignmentManager schoolId={m.school_id} teachers={teachers} classes={(classRows||[]) as ClassChoice[]} subjects={(subjectRows||[]) as SubjectChoice[]}/></section><section className="panel data-panel"><h3>Taklif qilingan xodimlar</h3><InviteForm schoolId={m.school_id}/></section></>}
 let rows:Record<string,unknown>[]=[];let count=0;
 if(sectionConfig.table){let q=db.from(sectionConfig.table).select("*").limit(100).throwOnError();if(sectionConfig.table!=="schools")q=q.eq("school_id",m.school_id);if(sectionConfig.filter==="student"&&m.role==="student")q=q.eq("student_id",user.id);if(sectionConfig.table==="notifications")q=q.eq("recipient_id",user.id);const result=await q;rows=(result.data||[]) as Record<string,unknown>[];count=rows.length;}
 const isInvite=section==="invitations";
 return <><div className="page-title-row"><div><Link href="/portal" className="back-link"><ArrowLeft size={14}/> Bosh sahifa</Link><h1>{isInvite?"Rollar va takliflar":sectionConfig.title}</h1><p>{sectionConfig.description}</p></div>{sectionConfig.table&&<span className="result-count">{count} ta yozuv</span>}</div>
 {isInvite?<><section className="panel form-panel"><div className="panel-heading"><div><h3>Yangi a’zoni taklif qilish</h3><p>Ommaviy ro‘yxatdan o‘tish o‘chirilgan. Faqat taklif qilingan hisoblar kiradi.</p></div><span className="secure-pill"><ShieldCheck size={14}/> Ruxsat nazorati</span></div><InviteForm schoolId={m.school_id}/></section><section className="privacy-note"><span>✉</span><span><b>Email taklifi</b><small>Foydalanuvchi havola orqali parol o‘rnatadi. Google orqali kirganda taklif qilingan email mos kelishi kerak.</small></span></section></>:sectionConfig.table?<section className="panel data-panel">{rows.length? <div className="table-wrap"><table><thead><tr>{sectionConfig.columns?.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id||i)}>{sectionConfig.columns?.map(([key])=><td key={key}>{format(row[key])}</td>)}</tr>)}</tbody></table></div>:<div className="empty-large"><span className="empty-illustration"><Inbox size={27}/></span><h3>Hozircha ma’lumot yo‘q</h3><p>{section==="grades"?"Baholar kiritilgach, shu bo‘limda ko‘rinadi.":"Maktab ma’lumotlari kiritilgach, shu yerda ko‘rinadi."}</p>{["admin","director"].includes(m.role)&&<Link href="/portal/invitations" className="outline-button"><Plus size={15}/> A’zoni taklif qilish</Link>}</div>}</section>:<section className="panel empty-large"><span className="empty-illustration"><Inbox size={27}/></span><h3>Bo‘lim sozlanmoqda</h3><p>{sectionConfig.description}. Ushbu bo‘lim Supabase sxemasiga tayyor; real yozuvlar kiritilgach ro‘yxatda chiqadi.</p></section>}
 <div className="privacy-note"><span>🔐</span><span><b>{roleLabels[m.role as keyof typeof roleLabels]} uchun ma’lumot</b><small>Ko‘rsatilgan ma’lumotlar maktabingiz ma’lumotlar bazasidan olinadi va hisob ruxsatlari bilan cheklanadi.</small></span></div></>;
}
function format(value:unknown){if(value==null)return "—";if(typeof value==="object")return JSON.stringify(value);const str=String(value);if(/\d{4}-\d{2}-\d{2}T/.test(str))return new Intl.DateTimeFormat("uz-UZ",{dateStyle:"medium",timeStyle:"short"}).format(new Date(str));return str.length>110?`${str.slice(0,110)}…`:str}
