"use client";
import { FormEvent, useState } from "react";
import { Crown, Users } from "lucide-react";

type Student = { id: string; name: string };
type Room = { id: string; name: string; grade_level: number; room: string | null; academic_year: string; class_leader_id: string | null; class_leader_name: string | null; homeroom_teacher_id: string | null; homeroom_teacher_name: string | null; students: Student[] };
export function ClassLeaderManager({ classes, schoolId, candidates }: { classes: Room[]; schoolId: string; candidates: Student[] }) {
  const [items, setItems] = useState(classes); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState("");
  async function addStudent(e: FormEvent<HTMLFormElement>, room: Room) { e.preventDefault(); const form = e.currentTarget; const studentId = String(new FormData(form).get("student") || ""); if (!studentId) return; setBusy(room.id); setNotice(""); try { const res = await fetch("/api/classes/students", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ schoolId, classId: room.id, studentId }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); const student = candidates.find(c => c.id === studentId); if (student) setItems(v => v.map(c => c.id === room.id ? { ...c, students: [...c.students, student] } : c)); setNotice(`${student?.name || "O‘quvchi"} ${room.name} sinfiga qo‘shildi.`); form.reset(); } catch (err) { setNotice(err instanceof Error ? err.message : "O‘quvchi sinfga qo‘shilmadi."); } finally { setBusy(""); } }
  async function assign(e: FormEvent<HTMLFormElement>, room: Room) { e.preventDefault(); const studentId = String(new FormData(e.currentTarget).get("student") || ""); if (!studentId) return; setBusy(room.id); setNotice(""); try { const res = await fetch("/api/classes/leader", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ classId: room.id, studentId }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); const student = room.students.find(s => s.id === studentId); setItems(v => v.map(c => c.id === room.id ? { ...c, class_leader_id: studentId, class_leader_name: student?.name || null } : c)); setNotice(`${room.name} sinfiga sardor tayinlandi.`); } catch (err) { setNotice(err instanceof Error ? err.message : "Sardor tayinlanmadi."); } finally { setBusy(""); } }
  return <div className="class-leader-list">{items.length ? items.map(room => { const available = candidates.filter(c => !room.students.some(s => s.id === c.id)); return <article className="class-leader-card" key={room.id}><div className="class-leader-head"><span className="empty-illustration"><Users size={20}/></span><div><h3>{room.name} sinf</h3><p>{room.grade_level}-sinf · {room.academic_year}{room.room ? ` · ${room.room}-xona` : ""}</p></div><span className="result-count">{room.students.length} o‘quvchi</span></div><p className="class-teacher-line">Sinf rahbari: <b>{room.homeroom_teacher_name || "Belgilanmagan"}</b></p><form className="class-leader-form" onSubmit={e => void addStudent(e, room)}><label>O‘quvchi qo‘shish<select name="student" defaultValue="" required disabled={!available.length}><option value="" disabled>{available.length ? "O‘quvchini tanlang" : "Yangi o‘quvchi yo‘q"}</option>{available.map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><button className="outline-button" disabled={busy === room.id || !available.length}>{busy === room.id ? "Saqlanmoqda…" : "Sinfga qo‘shish"}</button></form><form className="class-leader-form" onSubmit={e => void assign(e, room)}><label><Crown size={15}/> Sinf sardori<select name="student" defaultValue={room.class_leader_id || ""} required disabled={!room.students.length}><option value="" disabled>O‘quvchini tanlang</option>{room.students.map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><button className="outline-button" disabled={busy === room.id || !room.students.length}>{busy === room.id ? "Saqlanmoqda…" : "Sardorni saqlash"}</button></form>{!room.students.length && <small>Avval maktabga taklif qilingan o‘quvchini ushbu sinfga qo‘shing.</small>}</article>; }) : <div className="empty-large"><span className="empty-illustration"><Users size={24}/></span><h3>Sinflar hali yaratilmagan</h3><p>Direktor yoki admin sinflarni bazaga qo‘shgandan so‘ng ularni shu yerda boshqarish mumkin.</p></div>}{notice && <p className="notice success" role="status">{notice}</p>}</div>;
}
