"use client";

import { FormEvent, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Eye, ImagePlus, Save } from "lucide-react";
import { createClient } from "@/lib/supabase/browser";
import { defaultSiteContact, SiteContact } from "@/lib/site-contact";

export function ContactAdminPanel({initial,userId}:{initial:SiteContact;userId:string}){
 const [form,setForm]=useState<SiteContact>(initial);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 async function save(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setBusy(true);setError("");setNotice("");const db=createClient();try{let imageUrl=form.image_url;if(file){if(file.size>50*1024*1024)throw new Error("Rasm 50 MB dan kichik bo‘lishi kerak.");const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`contact/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await db.storage.from("mx-tour-assets").upload(path,file,{upsert:false,contentType:file.type});if(uploadError)throw uploadError;imageUrl=db.storage.from("mx-tour-assets").getPublicUrl(path).data.publicUrl}const payload={...form,title:form.title.trim(),body:form.body.trim(),phone:form.phone.trim(),telegram_handle:form.telegram_handle.replace(/^@/,"").trim(),instagram_handle:form.instagram_handle.replace(/^@/,"").trim(),image_url:imageUrl,updated_by:userId,updated_at:new Date().toISOString()};const {error:e}=await db.from("site_contact").upsert(payload,{onConflict:"id"});if(e)throw e;setForm(payload);setFile(null);setNotice("Aloqa sahifasi yangilandi.")}catch(e){setError(e instanceof Error?e.message:"Saqlash amalga oshmadi. Migratsiya va admin ruxsatini tekshiring.")}finally{setBusy(false)}}
 return <div className="contact-admin"><header className="contact-admin-head"><div><span className="eyebrow">MAKTAB X · ADMIN</span><h1>Aloqa sahifasini tahrirlash</h1><p>Ommaviy sahifadagi ma’lumot, rasm va aloqa tugmalarini boshqaring.</p></div><Link className="contact-preview" href="/contact" target="_blank"><Eye size={15}/> Sahifani ko‘rish</Link></header><div className="contact-admin-grid"><section className="contact-admin-preview">{form.image_url?<img src={form.image_url} alt="Aloqa sahifasi rasmi"/>:<Image src="/assets/contact-hero.png" alt="Aloqa sahifasi rasmi" width={800} height={540}/>}<div><b>{form.title||defaultSiteContact.title}</b><p>{form.body||defaultSiteContact.body}</p><small>Telefon · Telegram · Instagram</small></div></section><form className="contact-admin-form" onSubmit={save}><label>Sahifa sarlavhasi<input required maxLength={100} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Qisqa ma’lumot<textarea required rows={4} maxLength={500} value={form.body} onChange={e=>setForm(v=>({...v,body:e.target.value}))}/></label><div className="contact-admin-row"><label>Telefon raqami<input required type="tel" value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} placeholder="+998950328088"/></label><label>Telegram username<input required value={form.telegram_handle} onChange={e=>setForm(v=>({...v,telegram_handle:e.target.value.replace(/^@/,"")}))} placeholder="maktabx.official"/></label><label>Instagram username<input required value={form.instagram_handle} onChange={e=>setForm(v=>({...v,instagram_handle:e.target.value.replace(/^@/,"")}))} placeholder="maktabx.official"/></label></div><label className="contact-upload">Sahifa rasmi<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?.name||"PNG, JPG yoki WEBP · 50 MB gacha"}</small><ImagePlus size={18}/></label>{error&&<p className="contact-error">{error}</p>}{notice&&<p className="contact-success">{notice}</p>}<div className="contact-admin-actions"><button type="button" onClick={()=>{setForm(defaultSiteContact);setFile(null)}}>Boshlang‘ich ma’lumot</button><button className="contact-save" disabled={busy}><Save size={15}/>{busy?"Saqlanmoqda…":"O‘zgarishlarni saqlash"}</button></div></form></div></div>
}
