"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AppRole, roleLabels } from "@/lib/roles";
import { createClient } from "@/lib/supabase/browser";
import { QrCode } from "@/components/qr-code";
import { ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Coins, FileText, Heart, ImagePlus, LibraryBig, LockKeyhole, MessageCircle, Plus, QrCode as QrIcon, ScanLine, Send, Sparkles, Star, Users, X } from "lucide-react";

type Section = "library" | "lessons" | "community" | "rewards" | "kitchen" | "cafeteria";
type Book = {id:string;title:string;author:string|null;language:string;license_label:string;source_url:string|null;file_path:string|null;cover_path:string|null;cover_url?:string;file_url?:string};
type Question = {id:string;lesson_id:string;question:string;choices:string[];explanation:string;position:number};
type Lesson = {id:string;title:string;subject:string;grade_level:number|null;description:string;content:string;questions:Question[];progress:{best_score:number;attempts:number}|null};
type Product = {id:string;name:string;description:string|null;cost:number;inventory:number|null;image_path:string|null;image_url?:string};
type Post = {id:string;author_id:string;body:string;media_path:string|null;media_url?:string;created_at:string;author:string;comments:{id:string;author_id:string;body:string;author:string}[];liked:boolean;likes:number;followed?:boolean;followCount:number};
type Props = {section:Section;schoolId:string;school:string;role:AppRole;userId:string;name:string};
const mascotPrompts=[
  {text:"Assalomu alaykum! Bugun kichik bir bilim sarguzashtiga tayyormisiz?",actions:["Ha, boshlaymiz!","Avval kitoblarni ko‘raman"]},
  {text:"Zo‘r! Har bir urinish — katta maqsadga bir qadam. Qaysi mavzu sizga qiziq?",actions:["Yangi mavzuni o‘rganaman","Natijalarimni ko‘raman"]},
  {text:"Bir sahifa, bir savol, bir yutuq. Davom etsak, bilimlarimiz yanada mustahkam bo‘ladi!",actions:["Davom etamiz","Keyinroq qaytaman"]},
];
const openLicenses=["Public domain / jamoat mulki","CC0","CC BY","CC BY-SA","Maktab litsenziyasi / ruxsati"];

export function InteractiveHub({section,schoolId,school,role,userId,name}:Props){
 const db=useMemo(()=>createClient(),[]); const [notice,setNotice]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [dialog,setDialog]=useState(0);
 const [books,setBooks]=useState<Book[]>([]); const [bookProgress,setBookProgress]=useState<Record<string,{last_page:number;percent:number}>>({});
 const [lessons,setLessons]=useState<Lesson[]>([]); const [posts,setPosts]=useState<Post[]>([]); const [products,setProducts]=useState<Product[]>([]);
 const [redemptionToken,setRedemptionToken]=useState(""); const [redemptionProduct,setRedemptionProduct]=useState(""); const [expirySeconds,setExpirySeconds]=useState(600); const [answers,setAnswers]=useState<Record<string,number>>({}); const [score,setScore]=useState<Record<string,number>|null>(null);
 const [scannerOpen,setScannerOpen]=useState(false); const [manualToken,setManualToken]=useState(""); const [scannerResult,setScannerResult]=useState(""); const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const scanningRef=useRef(false);
 const staffCanPublish=["admin","director","teacher"].includes(role); const staffCanSell=["admin","director","cook"].includes(role); const isStudent=role==="student";
 const [bookForm,setBookForm]=useState(false); const [lessonForm,setLessonForm]=useState(false); const [productForm,setProductForm]=useState(false); const [postDraft,setPostDraft]=useState("");
 const [lessonDraft,setLessonDraft]=useState({title:"",subject:"",grade:"",description:"",content:"",questions:[{question:"",choices:["","",""],answer:0,explanation:""}]});
 const header=useMemo(()=>({library:["MAKTAB KUTUBXONASI","O‘qish — yangi olamlarga sayohat","Maktab ulashgan va ochiq litsenziyali asarlarni shu yerdan o‘qing."],lessons:["BILIM O‘YINLARI","Har bir mavzu — yangi sarguzasht","Qisqa darsni o‘rganing, savollarni yeching, yutug‘ingizni kuzating."],community:["MAKTAB HAMJAMIYATI","Bir maktab, ko‘p yaxshi fikrlar","Maktabingizdagi o‘quvchi, ustoz va ota-onalar bilan ulaning."],rewards:["X COIN · COINSHOP","Bilimingizni yutuqqa aylantiring","Mahsulot tanlang. QR faqat oshpaz onlayn tasdiqlagach bir martagina ishlaydi."],kitchen:["OSHXONA ISH JOYI","QR’ni skanerlab, berilgan mahsulotni tasdiqlang","Har QR bir marta va internet orqali tekshiriladi."],cafeteria:["OSHXONA VA COINSHOP","Mahsulot qo‘shing, suratini tanlang","Narxni X Coin’da belgilang; o‘quvchi QR oladi va oshpaz tekshiradi."]} as const)[section],[section]);
 const [eyebrow,title,subtitle]=header;

 const signed = useCallback(async(path:string|null)=>{if(!path)return undefined;const {data}=await db.storage.from("school-assets").createSignedUrl(path,3600);return data?.signedUrl},[db]);
 const load = useCallback(async()=>{
   setError("");
   if(section==="library"){
     const [{data,error:e},progress]=await Promise.all([db.from("reading_books").select("id,title,author,language,license_label,source_url,file_path,cover_path").eq("school_id",schoolId).order("created_at",{ascending:false}),db.from("reading_progress").select("book_id,last_page,percent").eq("school_id",schoolId).eq("user_id",userId)]);
     if(e){setError("Kutubxona bazaga ulanmayapti. Supabase migratsiyasini qo‘llang.");return}
     const list=await Promise.all((data||[]).map(async b=>({...b,cover_url:await signed(b.cover_path),file_url:await signed(b.file_path)} as Book)));
     setBooks(list);setBookProgress(Object.fromEntries((progress.data||[]).map(x=>[x.book_id,{last_page:x.last_page,percent:x.percent}])));
   }
   if(section==="lessons"){
     const {data,error:e}=await db.from("learning_lessons").select("id,title,subject,grade_level,description,content").eq("school_id",schoolId).not("published_at","is",null).order("published_at",{ascending:false});
     if(e){setError("Darslar bazasiga ulanmayapti. Supabase migratsiyasini qo‘llang.");return}
     const ids=(data||[]).map(x=>x.id);let qdata:Question[]=[];let pmap:Record<string,{best_score:number;attempts:number}>={};
     if(ids.length){const [q,p]=await Promise.all([db.from("learning_questions").select("id,lesson_id,question,choices,explanation,position").in("lesson_id",ids).order("position"),db.from("learning_progress").select("lesson_id,best_score,attempts").eq("school_id",schoolId).eq("student_id",userId)]);qdata=(q.data||[]) as Question[];pmap=Object.fromEntries((p.data||[]).map(x=>[x.lesson_id,{best_score:x.best_score,attempts:x.attempts}]));}
     setLessons((data||[]).map(x=>({...x,questions:qdata.filter(q=>q.lesson_id===x.id),progress:pmap[x.id]||null})) as Lesson[]);
   }
   if(section==="rewards"||section==="cafeteria"){
     const {data,error:e}=await db.from("rewards").select("id,name,description,cost,inventory,image_path,active").eq("school_id",schoolId).eq("active",true).order("created_at",{ascending:false});
     if(e){setError("CoinShop bazaga ulanmayapti. Supabase migratsiyasini qo‘llang.");return}
     setProducts(await Promise.all((data||[]).map(async x=>({...x,image_url:await signed(x.image_path)}))));
   }
   if(section==="community"){
     const {data,error:e}=await db.from("school_posts").select("id,author_id,body,media_path,created_at").eq("school_id",schoolId).is("moderated_at",null).order("created_at",{ascending:false}).limit(80);
     if(e){setError("Maktab hamjamiyati bazaga ulanmayapti. Supabase migratsiyasini qo‘llang.");return}
     const ids=(data||[]).map(p=>p.id);const authors=[...new Set((data||[]).map(p=>p.author_id))];
     const [profiles,comments,likes,follows,followerRows]=await Promise.all([
       authors.length?db.from("mx_profiles").select("id,full_name").in("id",authors):Promise.resolve({data:[]}),
       ids.length?db.from("school_post_comments").select("id,post_id,author_id,body").in("post_id",ids).order("created_at"):Promise.resolve({data:[]}),
       ids.length?db.from("school_post_likes").select("post_id,user_id").in("post_id",ids):Promise.resolve({data:[]}),
       db.from("school_follows").select("following_id").eq("school_id",schoolId).eq("follower_id",userId),
       db.from("school_follows").select("following_id").eq("school_id",schoolId),
     ]);
     const names=Object.fromEntries((profiles.data||[]).map((p:{id:string;full_name:string})=>[p.id,p.full_name]));const followed=new Set((follows.data||[]).map((f:{following_id:string})=>f.following_id));const followCount:Record<string,number>={};for(const f of followerRows.data||[])followCount[f.following_id]=(followCount[f.following_id]||0)+1;
     setPosts(await Promise.all((data||[]).map(async p=>({id:p.id,author_id:p.author_id,body:p.body,media_path:p.media_path,media_url:await signed(p.media_path),created_at:p.created_at,author:names[p.author_id]||"Maktab a’zosi",comments:(comments.data||[]).filter((c:{post_id:string})=>c.post_id===p.id).map((c:{id:string;author_id:string;body:string})=>({id:c.id,author_id:c.author_id,body:c.body,author:names[c.author_id]||"Maktab a’zosi"})),liked:(likes.data||[]).some((l:{post_id:string;user_id:string})=>l.post_id===p.id&&l.user_id===userId),likes:(likes.data||[]).filter((l:{post_id:string})=>l.post_id===p.id).length,followed:followed.has(p.author_id),followCount:followCount[p.author_id]||0}))));
   }
 },[db,section,schoolId,userId,signed]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{if(!redemptionToken)return;const timer=window.setInterval(()=>setExpirySeconds(s=>{if(s<=1){window.clearInterval(timer);setRedemptionToken("");setError("CoinShop QR muddati tugadi. Yangi kod yarating.");return 0}return s-1}),1000);return()=>window.clearInterval(timer)},[redemptionToken]);

 async function upload(file:File,folder:string){if(file.size>25*1024*1024)throw new Error("Fayl hajmi 25 MB dan oshmasin.");const ext=file.name.split(".").pop()?.toLowerCase()||"bin";const path=`${schoolId}/${folder}/${crypto.randomUUID()}.${ext}`;const mime=file.type||(ext==="pdf"?"application/pdf":ext==="epub"?"application/epub+zip":ext==="png"?"image/png":ext==="webp"?"image/webp":ext==="jpg"||ext==="jpeg"?"image/jpeg":"application/octet-stream");const {error:e}=await db.storage.from("school-assets").upload(path,file,{contentType:mime,upsert:false});if(e)throw e;return path}
 function sayNext(){setDialog(v=>(v+1)%mascotPrompts.length);setNotice("")}
 async function saveBook(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setBusy(true);setError("");setNotice("");try{const f=new FormData(ev.currentTarget);const title=String(f.get("title")||"").trim();const sourceUrl=String(f.get("source_url")||"").trim();const file=f.get("book_file");const cover=f.get("cover");let file_path:string|null=null;let cover_path:string|null=null;if(file instanceof File&&file.size)file_path=await upload(file,"books");if(cover instanceof File&&cover.size)cover_path=await upload(cover,"covers");if(!file_path&&!sourceUrl)throw new Error("Kitob fayli yoki ochiq manba havolasini kiriting.");const {error:e}=await db.from("reading_books").insert({school_id:schoolId,title,author:String(f.get("author")||"")||null,language:String(f.get("language")||"uz"),license_label:String(f.get("license")||""),source_url:sourceUrl||null,file_path,cover_path,published_by:userId});if(e)throw e;setNotice("Kitob kutubxonaga qo‘shildi.");setBookForm(false);await load()}catch(e){setError(e instanceof Error?e.message:"Kitob saqlanmadi.")}finally{setBusy(false)}}
 async function updateProgress(book:Book,percent:number){const page=Math.max(1,Number(window.prompt("Qaysi sahifagacha o‘qidingiz?",String(bookProgress[book.id]?.last_page||1))||1));const {error:e}=await db.from("reading_progress").upsert({school_id:schoolId,book_id:book.id,user_id:userId,last_page:page,percent,finished_at:percent===100?new Date().toISOString():null,updated_at:new Date().toISOString()});if(e)setError(e.message);else{setBookProgress(v=>({...v,[book.id]:{last_page:page,percent}}));setNotice(percent===100?"Kitob mutolaasi yakunlandi. Barakalla!":"O‘qish jarayoni saqlandi.")}}
 function changeQuestion(index:number,field:"question"|"explanation"|"answer",value:string|number){setLessonDraft(v=>({...v,questions:v.questions.map((q,i)=>i===index?{...q,[field]:value}:q)}))}
 function changeChoice(qi:number,ci:number,value:string){setLessonDraft(v=>({...v,questions:v.questions.map((q,i)=>i===qi?{...q,choices:q.choices.map((c,j)=>j===ci?value:c)}:q)}))}
 async function saveLesson(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const questions=lessonDraft.questions.filter(q=>q.question.trim()&&q.choices.every(c=>c.trim())).map((q,i)=>({question:q.question.trim(),choices:q.choices,answer_key:q.answer,explanation:q.explanation.trim(),position:i}));if(!questions.length){setError("Kamida bitta savol va to‘ldirilgan javoblar kerak.");return}setBusy(true);setError("");try{const lessonData={school_id:schoolId,title:lessonDraft.title.trim(),subject:lessonDraft.subject.trim(),grade_level:lessonDraft.grade?Number(lessonDraft.grade):null,description:lessonDraft.description.trim(),content:lessonDraft.content.trim(),created_by:userId,published_at:new Date().toISOString()};const {data:lesson,error:e}=await db.from("learning_lessons").insert(lessonData).select("id").single();if(e||!lesson)throw e||new Error("Dars saqlanmadi.");const {error:qe}=await db.from("learning_questions").insert(questions.map(q=>({...q,lesson_id:lesson.id})));if(qe)throw qe;setLessonForm(false);setNotice("O‘yinli mini-dars nashr qilindi.");setLessonDraft({title:"",subject:"",grade:"",description:"",content:"",questions:[{question:"",choices:["","",""],answer:0,explanation:""}]});await load()}catch(e){setError(e instanceof Error?e.message:"Dars saqlanmadi.")}finally{setBusy(false)}}
 async function submitQuiz(lesson:Lesson){if(!lesson.questions.length){setError("Bu dars uchun savollar hali qo‘shilmagan.");return}setBusy(true);setError("");setScore(null);try{const {data,error:e}=await db.rpc("submit_learning_quiz",{target_lesson:lesson.id,submitted_answers:answers});if(e)throw e;setScore(data as Record<string,number>);await load()}catch(e){setError(e instanceof Error?e.message:"Javoblar saqlanmadi.")}finally{setBusy(false)}}
 async function saveProduct(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setBusy(true);setError("");try{const f=new FormData(ev.currentTarget);const photo=f.get("photo");let image_path:string|null=null;if(photo instanceof File&&photo.size)image_path=await upload(photo,"coinshop");const {error:e}=await db.from("rewards").insert({school_id:schoolId,name:String(f.get("name")||"").trim(),description:String(f.get("description")||"").trim()||null,cost:Number(f.get("cost")),inventory:f.get("inventory")?Number(f.get("inventory")):null,image_path,created_by:userId,active:true});if(e)throw e;setProductForm(false);setNotice("Mahsulot CoinShop’ga qo‘shildi.");await load()}catch(e){setError(e instanceof Error?e.message:"Mahsulot saqlanmadi.")}finally{setBusy(false)}}
 async function askForProduct(product:Product){setBusy(true);setError("");setRedemptionToken("");try{const r=await fetch("/api/coinshop/redeem",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rewardId:product.id})});const data=await r.json();if(!r.ok)throw new Error(data.error||"QR yaratilmadi.");setExpirySeconds(600);setRedemptionToken(data.token);setRedemptionProduct(data.product);setNotice("QR 10 daqiqa davomida amal qiladi. Oshpaz skanerlaganda Coin yechiladi.")}catch(e){setError(e instanceof Error?e.message:"QR yaratilmadi.")}finally{setBusy(false)}}
 async function savePost(ev:FormEvent<HTMLFormElement>){ev.preventDefault();if(!postDraft.trim()){setError("Xabar matnini yozing.");return}setBusy(true);setError("");try{const form=ev.currentTarget;const file=(new FormData(form).get("photo"));let media_path:string|null=null;if(file instanceof File&&file.size)media_path=await upload(file,"community");const {error:e}=await db.from("school_posts").insert({school_id:schoolId,author_id:userId,body:postDraft.trim(),media_path});if(e)throw e;setPostDraft("");form.reset();setNotice("Postingiz maktabingiz hamjamiyatiga joylandi.");await load()}catch(e){setError(e instanceof Error?e.message:"Post joylanmadi.")}finally{setBusy(false)}}
 async function addComment(ev:FormEvent<HTMLFormElement>,post:Post){ev.preventDefault();const form=ev.currentTarget;const text=String(new FormData(form).get("comment")||"").trim();if(!text)return;const {error:e}=await db.from("school_post_comments").insert({school_id:schoolId,post_id:post.id,author_id:userId,body:text});if(e)setError(e.message);else{form.reset();await load()}}
 async function toggleLike(post:Post){const result=post.liked?await db.from("school_post_likes").delete().eq("post_id",post.id).eq("user_id",userId):await db.from("school_post_likes").insert({school_id:schoolId,post_id:post.id,user_id:userId});if(result.error)setError(result.error.message);else await load()}
 async function toggleFollow(post:Post&{followed?:boolean}){const result=post.followed?await db.from("school_follows").delete().eq("school_id",schoolId).eq("follower_id",userId).eq("following_id",post.author_id):await db.from("school_follows").insert({school_id:schoolId,follower_id:userId,following_id:post.author_id});if(result.error)setError(result.error.message);else await load()}
 async function scan(token:string){if(scanningRef.current)return;scanningRef.current=true;setScannerResult("");setError("");try{const r=await fetch("/api/kitchen/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})});const data=await r.json();if(!r.ok)throw new Error(data.error||"QR tasdiqlanmadi.");setScannerResult(`${data.product} berildi · ${data.cost} Coin olindi · qoldiq ${data.remaining} Coin`);setManualToken("")}catch(e){setError(e instanceof Error?e.message:"QR tekshirilmadi.")}finally{scanningRef.current=false}}
 useEffect(()=>{if(!scannerOpen)return;let alive=true;let timer:number|undefined;async function open(){const Detector=(window as unknown as {BarcodeDetector?:new(o:{formats:string[]})=>{detect:(video:HTMLVideoElement)=>Promise<{rawValue:string}[]>}}).BarcodeDetector;if(!Detector){setError("Brauzer QR kamerani qo‘llamaydi. Kamera skaneri yoki USB skaner maydonidan foydalaning.");return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});if(!alive){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}const detector=new Detector({formats:["qr_code"]});timer=window.setInterval(async()=>{if(!alive||!videoRef.current||scanningRef.current)return;try{const codes=await detector.detect(videoRef.current);if(codes[0]?.rawValue)await scan(codes[0].rawValue)}catch{/* Camera may still be focusing. */}},650)}catch{setError("Kameraga ruxsat bering yoki kodni qo‘lda skanerlang.")}}void open();return()=>{alive=false;if(timer)window.clearInterval(timer);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null}},[scannerOpen]);

 return <div className="learning-hub">
  <header className="hub-hero"><div className="hub-hero-copy"><div className="hub-eyebrow"><Sparkles size={14}/>{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p><div className="hub-school"><Users size={14}/>{school} <span>·</span> {roleLabels[role]}</div></div><div className="hub-mascot-wrap"><Image className="hub-mascot" src="/assets/x-bilimcha.png" alt="Bilimcha — MAKTAB X bilim yordamchisi" width={260} height={310} priority/><div className="hub-mascot-bubble"><strong>Bilimcha</strong><span>{mascotPrompts[dialog].text}</span><div>{mascotPrompts[dialog].actions.map(a=><button key={a} onClick={sayNext}>{a}<ArrowRight size={12}/></button>)}</div></div></div></header>
  {error&&<div className="hub-notice error" role="alert">{error}</div>}{notice&&<div className="hub-notice success" role="status"><Check size={16}/>{notice}</div>}

  {section==="library"&&<section className="hub-section"><div className="hub-section-title"><div><span className="hub-eyebrow"><LibraryBig size={13}/> MUTOLAA VA KITOBLAR</span><h2>Kitob javoni</h2><p>Har bir kitob maktab ruxsati yoki ko‘rsatilgan ochiq litsenziya bilan ulashiladi.</p></div>{staffCanPublish&&<button className="hub-primary" onClick={()=>setBookForm(!bookForm)}><Plus size={16}/> Kitob qo‘shish</button>}</div>
   {bookForm&&<form className="hub-form" onSubmit={saveBook}><div className="hub-form-title"><BookOpen size={18}/><div><b>Kitobni kutubxonaga joylash</b><small>PDF/EPUB faylini yoki ochiq litsenziyali manba havolasini kiriting.</small></div><button type="button" className="hub-close" onClick={()=>setBookForm(false)}><X size={17}/></button></div><div className="hub-fields"><label>Kitob nomi<input required name="title" maxLength={180} placeholder="Masalan: Ochiq ta’lim qo‘llanmasi"/></label><label>Muallif<input name="author" maxLength={140} placeholder="Muallif ismi"/></label><label>Til<select name="language"><option value="uz">O‘zbek tili</option><option value="ru">Русский</option><option value="en">English</option><option value="other">Boshqa</option></select></label><label>Litsenziya<select required name="license">{openLicenses.map(l=><option key={l}>{l}</option>)}</select></label><label className="file-drop"><FileText size={19}/> PDF yoki EPUB fayl <input name="book_file" type="file" accept="application/pdf,.epub,application/epub+zip"/></label><label>Yoki ochiq kitob manzili<input name="source_url" type="url" placeholder="https://…"/></label><label className="file-drop"><ImagePlus size={19}/> Muqova rasmi (ixtiyoriy)<input name="cover" type="file" accept="image/png,image/jpeg,image/webp"/></label></div><p className="hub-disclaimer"><LockKeyhole size={13}/> Litsenziyasi belgilanmagan yoki maktabga ruxsatsiz asarni yuklamang.</p><button className="hub-primary" disabled={busy}>{busy?"Saqlanmoqda…":"Kutubxonaga qo‘shish"}</button></form>}
   <div className="hub-card-grid books-grid">{books.map(b=><article className="hub-book-card" key={b.id}>{b.cover_url?<img src={b.cover_url} alt={`${b.title} muqovasi`} className="book-cover"/>:<div className="book-cover empty-cover"><BookOpen size={36}/></div>}<div className="hub-book-body"><span className="hub-tag">{b.language.toUpperCase()} · {b.license_label}</span><h3>{b.title}</h3><p>{b.author||"Muallif ko‘rsatilmagan"}</p>{b.source_url&&<a className="hub-link" href={b.source_url} target="_blank" rel="noreferrer">Ochiq manbani ochish <ArrowRight size={13}/></a>}{b.file_url&&<a className="hub-link" href={b.file_url} target="_blank" rel="noreferrer"><BookOpen size={13}/> Kitobni o‘qish <ArrowRight size={13}/></a>}<div className="reading-progress"><span style={{width:`${bookProgress[b.id]?.percent||0}%`}}/></div><small>{bookProgress[b.id]?`${bookProgress[b.id].percent}% · ${bookProgress[b.id].last_page}-sahifa o‘qildi`:"Hali boshlanmagan"}</small><div className="book-actions"><button onClick={()=>void updateProgress(b,Math.min(100,(bookProgress[b.id]?.percent||0)+10))}>O‘qishni davom ettirish</button><button aria-label="Kitobni tugatdim" onClick={()=>void updateProgress(b,100)}><Check size={14}/> Tugatdim</button></div></div></article>)}{!books.length&&<div className="hub-empty"><LibraryBig/><h3>Kutubxonada kitoblar hali yo‘q</h3><p>Admin, direktor yoki ustoz birinchi litsenziyali kitobni joylagach, shu yerda ko‘rinadi.</p></div>}</div>
  </section>}

  {section==="lessons"&&<section className="hub-section"><div className="hub-section-title"><div><span className="hub-eyebrow"><Star size={13}/> BILIM + O‘YIN</span><h2>Qisqa darslar va topshiriqlar</h2><p>To‘g‘ri javoblaringiz va o‘rganish urinishlari profilingizga yoziladi.</p></div>{staffCanPublish&&<button className="hub-primary" onClick={()=>setLessonForm(!lessonForm)}><Plus size={16}/> Dars yaratish</button>}</div>
   {lessonForm&&<form className="hub-form" onSubmit={saveLesson}><div className="hub-form-title"><Sparkles size={18}/><div><b>Yangi o‘yinli mini-dars</b><small>Darsni nashr qiling va savollar bilan mustahkamlang.</small></div><button type="button" className="hub-close" onClick={()=>setLessonForm(false)}><X size={17}/></button></div><div className="hub-fields"><label>Dars mavzusi<input required value={lessonDraft.title} onChange={e=>setLessonDraft(v=>({...v,title:e.target.value}))} maxLength={180}/></label><label>Fan<input required value={lessonDraft.subject} onChange={e=>setLessonDraft(v=>({...v,subject:e.target.value}))} maxLength={80} placeholder="Matematika, tarix…"/></label><label>Sinf<input type="number" min="1" max="11" value={lessonDraft.grade} onChange={e=>setLessonDraft(v=>({...v,grade:e.target.value}))}/></label><label>Qisqa tavsif<input value={lessonDraft.description} onChange={e=>setLessonDraft(v=>({...v,description:e.target.value}))} maxLength={240}/></label><label className="full-field">Dars matni<textarea required rows={4} value={lessonDraft.content} onChange={e=>setLessonDraft(v=>({...v,content:e.target.value}))} maxLength={5000} placeholder="O‘quvchiga mavzuni sodda tilda tushuntiring…"/></label></div>{lessonDraft.questions.map((q,i)=><div className="question-editor" key={i}><div className="question-editor-top"><b>{i+1}-savol</b>{lessonDraft.questions.length>1&&<button type="button" onClick={()=>setLessonDraft(v=>({...v,questions:v.questions.filter((_,j)=>j!==i)}))}><X size={15}/></button>}</div><label>Savol matni<input required value={q.question} onChange={e=>changeQuestion(i,"question",e.target.value)} maxLength={360}/></label><div className="hub-fields">{q.choices.map((c,j)=><label key={j}>Javob {String.fromCharCode(65+j)}<input required value={c} onChange={e=>changeChoice(i,j,e.target.value)}/></label>)}</div><div className="hub-fields"><label>To‘g‘ri javob<select value={q.answer} onChange={e=>changeQuestion(i,"answer",Number(e.target.value))}>{q.choices.map((_,j)=><option key={j} value={j}>{String.fromCharCode(65+j)}</option>)}</select></label><label>Izoh<input value={q.explanation} onChange={e=>changeQuestion(i,"explanation",e.target.value)} placeholder="Javob nima uchun to‘g‘ri?"/></label></div></div>)}<div className="hub-form-actions"><button type="button" className="hub-secondary" onClick={()=>setLessonDraft(v=>({...v,questions:[...v.questions,{question:"",choices:["","",""],answer:0,explanation:""}]}))}><Plus size={14}/> Savol qo‘shish</button><button className="hub-primary" disabled={busy}>{busy?"Nashr qilinmoqda…":"Darsni nashr qilish"}</button></div></form>}
   <div className="lesson-list">{lessons.map((l,li)=><article className="lesson-card" key={l.id}><div className="lesson-card-top"><div className="lesson-number">{String(li+1).padStart(2,"0")}</div><div className="lesson-title"><span className="hub-tag">{l.subject}{l.grade_level?` · ${l.grade_level}-sinf`:""}</span><h3>{l.title}</h3><p>{l.description}</p></div>{l.progress&&<div className="lesson-score"><Star size={16}/><b>{l.progress.best_score}%</b><small>{l.progress.attempts} urinish</small></div>}</div><details className="lesson-details"><summary><BookOpen size={14}/> Darsni o‘qish <ChevronRight size={14}/></summary><div className="lesson-content">{l.content}</div></details><div className="lesson-quiz">{l.questions.length?<><h4><CircleHelp size={16}/> Bilimingizni sinab ko‘ring <span>{l.questions.length} savol</span></h4>{l.questions.map((q,qi)=><fieldset className="quiz-question" key={q.id}><legend>{qi+1}. {q.question}</legend><div>{q.choices.map((choice,i)=><label className={`quiz-choice ${answers[q.id]===i?"choice-selected":""}`} key={i}><input type="radio" name={q.id} checked={answers[q.id]===i} onChange={()=>setAnswers(v=>({...v,[q.id]:i}))}/><span>{String.fromCharCode(65+i)}</span>{choice}</label>)}</div></fieldset>)}<button className="hub-primary" disabled={busy||l.questions.some(q=>answers[q.id]===undefined)} onClick={()=>void submitQuiz(l)}>{busy?"Tekshirilmoqda…":"Javoblarni tekshirish"}<ArrowRight size={15}/></button>{score&&<div className="quiz-result"><Image src="/assets/x-bilimcha.png" alt="Bilimcha" width={74} height={90}/><div><b>{score.score>=80?"Ajoyib natija!":"Yaxshi urinish — yana mashq qilamiz!"}</b><p>{score.correct}/{score.total} to‘g‘ri javob · {score.score}%</p>{l.questions.map(q=><small key={q.id}>💡 {q.explanation}</small>)}</div></div>}</>:<p className="muted-line">Bu dars uchun savollar qo‘shilmagan.</p>}</div></article>)}{!lessons.length&&<div className="hub-empty"><Image src="/assets/x-bilimcha.png" alt="Bilimcha kutmoqda" width={100} height={120}/><h3>Yangi sarguzashtga tayyormisiz?</h3><p>Bu yerda hozircha nashr qilingan mini-dars yo‘q. Ustozlar haqiqiy mavzu va topshiriqlarni qo‘shishi mumkin.</p></div>}</div>
  </section>}

  {section==="community"&&<section className="community-layout"><div className="community-stream"><form className="post-composer" onSubmit={savePost}><div className="composer-avatar">{name.slice(0,1).toUpperCase()}</div><div><textarea value={postDraft} onChange={e=>setPostDraft(e.target.value)} maxLength={2000} placeholder="Maktabingizga nima ulashmoqchisiz?"/><div className="composer-tools"><label><ImagePlus size={16}/> Rasm qo‘shish<input type="file" name="photo" accept="image/png,image/jpeg,image/webp"/></label><button className="hub-primary" disabled={busy||!postDraft.trim()}><Send size={14}/> Joylash</button></div></div></form><div className="school-only"><LockKeyhole size={14}/> Bu tarmoq faqat {school} a’zolariga ko‘rinadi. Admin va direktor maktab postlarini boshqarishi mumkin.</div>
   {posts.map(post=><article className="post-card" key={post.id}><header><div className="composer-avatar">{post.author.slice(0,1).toUpperCase()}</div><div><b>{post.author}</b><small>{new Intl.DateTimeFormat("uz-UZ",{dateStyle:"medium",timeStyle:"short"}).format(new Date(post.created_at))}</small></div>{post.author_id!==userId&&<button className="follow-button" onClick={()=>void toggleFollow(post as Post&{followed?:boolean})}><Users size={14}/>{(post as Post&{followed?:boolean}).followed?"Obunadasiz":"Obuna bo‘lish"}</button>}</header><p className="post-body">{post.body}</p>{post.media_url&&<img className="post-image" src={post.media_url} alt="Maktab posti rasmi"/>}<div className="post-actions"><button className={post.liked?"liked":""} onClick={()=>void toggleLike(post)}><Heart size={17} fill={post.liked?"currentColor":"none"}/>{post.likes}</button><span><MessageCircle size={16}/>{post.comments.length} izoh</span></div><div className="post-comments">{post.comments.map(c=><p key={c.id}><b>{c.author}</b> {c.body}</p>)}<form onSubmit={e=>void addComment(e,post)}><input name="comment" maxLength={1000} placeholder="Fikr bildiring…"/><button aria-label="Izoh yuborish"><Send size={15}/></button></form></div></article>)}{!posts.length&&<div className="hub-empty"><MessageCircle/><h3>Hamjamiyatga birinchi bo‘lib fikr ulashing</h3><p>Postlar faqat maktabingizda ko‘rinadi; begona maktablar bilan aralashmaydi.</p></div>}</div><aside className="community-aside"><div className="aside-mascot"><Image src="/assets/x-bilimcha.png" alt="Bilimcha" width={132} height={160}/><b>Hurmat bilan ulashing 💙</b><p>Maktab hamjamiyati o‘zaro hurmat, foydali bilim va xavfsiz muloqot uchun.</p></div><div className="aside-card"><b>Ushbu maktab</b><span>{school}</span><small>Postlar: {posts.length}</small><small>Obunachilar maktab doirasida</small></div></aside></section>}

  {(section==="rewards"||section==="cafeteria")&&<section className="hub-section"><div className="hub-section-title"><div><span className="hub-eyebrow"><Coins size={14}/> {isStudent?"YUTUQ VA MOTIVATSIYA":"MAKTAB DO‘KONI"}</span><h2>{isStudent?"Mukofotni tanlang":"Coinshop mahsulotlari"}</h2><p>{isStudent?"Oshpaz skanerlaganda Coin yechiladi. QR 10 daqiqa va bir marta ishlaydi.":"Mahsulotga narx, rasm va zaxira kiriting; oshpaz QR orqali topshiradi."}</p></div>{staffCanSell&&<button className="hub-primary" onClick={()=>setProductForm(!productForm)}><Plus size={16}/> Mahsulot qo‘shish</button>}</div>
   {productForm&&<form className="hub-form" onSubmit={saveProduct}><div className="hub-form-title"><Coins size={18}/><div><b>Coinshop’ga mahsulot joylash</b><small>Oshpaz yoki rahbariyat yuklagan mahsulot o‘quvchilarga maktab ichida ko‘rinadi.</small></div><button type="button" className="hub-close" onClick={()=>setProductForm(false)}><X size={17}/></button></div><div className="hub-fields"><label>Mahsulot nomi<input required name="name" maxLength={120} placeholder="Masalan: Maktab oshxonasi burgeri"/></label><label>Narxi (X Coin)<input required name="cost" type="number" min="1" max="100000"/></label><label>Zaxira miqdori<input name="inventory" type="number" min="0" placeholder="Bo‘sh qoldirilsa cheklanmaydi"/></label><label>Tavsif<input name="description" maxLength={400} placeholder="Tarkibi yoki olish joyi"/></label><label className="file-drop full-field"><ImagePlus size={19}/> Mahsulot rasmini ichki xotiradan tanlang<input required name="photo" type="file" accept="image/png,image/jpeg,image/webp"/></label></div><p className="hub-disclaimer"><LockKeyhole size={13}/> Mahsulot rasmi maktabning yopiq Supabase xotirasida saqlanadi.</p><button className="hub-primary" disabled={busy}>{busy?"Yuklanmoqda…":"Mahsulotni saqlash"}</button></form>}
   {redemptionToken&&<div className="redemption-ticket"><button className="hub-close" aria-label="QR oynasini yopish" onClick={()=>setRedemptionToken("")}><X size={17}/></button><div><span className="hub-eyebrow"><QrIcon size={14}/> OSHPAZGA KO‘RSATING</span><h3>{redemptionProduct}</h3><p>Oshpaz QR’ni skanerlaganda mahsulot beriladi va Coin yechiladi. Kod muddati tugasa, qayta yarating.</p><span className="qr-countdown"><Clock3 size={13}/> {String(Math.floor(expirySeconds/60)).padStart(2,"0")}:{String(expirySeconds%60).padStart(2,"0")} · bir martalik QR</span></div><QrCode value={redemptionToken}/></div>}
   <div className="hub-card-grid product-grid">{products.map(product=><article className="product-card" key={product.id}>{product.image_url?<img src={product.image_url} alt={product.name}/>:<div className="product-empty-image"><ImagePlus size={32}/></div>}<div className="product-info"><div className="product-card-title"><h3>{product.name}</h3><span className="coin-price"><Coins size={14}/>{product.cost}</span></div>{product.description&&<p>{product.description}</p>}<small>{product.inventory===null?"Cheklanmagan":`${product.inventory} dona qoldi`}</small>{isStudent&&<button className="hub-primary" disabled={busy||product.inventory===0} onClick={()=>void askForProduct(product)}><QrIcon size={15}/>{busy?"QR tayyorlanmoqda…":"Coin’ga almashtirish"}</button>}</div></article>)}{!products.length&&<div className="hub-empty"><Coins/><h3>CoinShop’da mahsulot hali yo‘q</h3><p>Admin, direktor yoki oshpaz rasm, narx va zaxirasi bilan haqiqiy mahsulot qo‘shishi mumkin.</p></div>}</div>
  </section>}

  {section==="kitchen"&&<section className="kitchen-panel"><div className="kitchen-callout"><div><span className="hub-eyebrow"><ScanLine size={14}/> BIR MARTALIK ONLAYN TEKSHIRUV</span><h2>O‘quvchining CoinShop QR’ini skanerlang</h2><p>Server QR muddati, maktab roli, mahsulot zaxirasi va Coin balansini tekshiradi. Shu kod qayta ishlatilmaydi.</p></div><button className="hub-primary" onClick={()=>{setScannerOpen(v=>!v);setScannerResult("")}}>{scannerOpen?<X size={16}/>:<ScanLine size={16}/>} {scannerOpen?"Skanerni yopish":"Kamerani ochish"}</button></div>{scannerOpen&&<div className="scanner-layout"><div className="camera-box"><video ref={videoRef} muted playsInline/><div className="scan-frame"><i/><i/><i/><i/></div></div><div><h3>Telefon kamerasini QR’ga qarating</h3><p>Yaxshi yorug‘likda telefonni barqaror tuting. Harid darhol tasdiqlanadi; offline rejimda ishlamaydi.</p><form className="manual-scan" onSubmit={e=>{e.preventDefault();if(manualToken.trim())void scan(manualToken.trim())}}><label>Qo‘lda yoki apparat skaneri bilan kiritish<input autoComplete="off" value={manualToken} onChange={e=>setManualToken(e.target.value)} placeholder="QR tokenini skanerlang"/></label><button className="hub-primary" disabled={!manualToken.trim()||busy}><ScanLine size={15}/> Tekshirish</button></form></div></div>}{scannerResult&&<div className="hub-notice success"><Check/>{scannerResult}</div>}</section>}
 </div>
}
