"use client";
import { FormEvent,useState } from "react";
import { School,UserPlus } from "lucide-react";

export function SchoolProvisionForm(){
 const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setNotice("");const f=new FormData(e.currentTarget);try{const res=await fetch("/api/platform/schools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("school"),slug:f.get("slug"),number:f.get("number"),province:f.get("province"),district:f.get("district"),address:f.get("address"),adminName:f.get("adminName"),adminEmail:f.get("adminEmail")})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Maktab biriktirilmadi");setNotice("Maktab bazaga qo‘shildi va boshlang‘ich admin uchun email taklifi yaratildi. Admin havoladan o‘z hisobini faollashtiradi.");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"Saqlanmadi") }finally{setBusy(false)}}
 return <form className="invite-form" onSubmit={submit}><div className="form-row"><div className="field"><label>Maktabning to‘liq nomi</label><input name="school" required minLength={3} placeholder="Masalan, 12-sonli umumta’lim maktabi"/></div><div className="field"><label>Unikal manzil kodi</label><input name="slug" required pattern="[a-zA-Z0-9-]{3,50}" placeholder="toshkent-12-maktab"/></div></div><div className="form-row"><div className="field"><label>Viloyat / Qoraqalpog‘iston</label><input name="province" required placeholder="Toshkent shahri"/></div><div className="field"><label>Tuman yoki shahar</label><input name="district" required placeholder="Yunusobod tumani"/></div><div className="field"><label>Maktab raqami</label><input name="number" placeholder="12"/></div></div><div className="field"><label>Manzil</label><input name="address" placeholder="Ko‘cha, uy"/></div><div className="form-row"><div className="field"><label>Birinchi adminning ismi</label><input name="adminName" required minLength={2} placeholder="Maktab admini"/></div><div className="field"><label>Birinchi adminning emaili</label><input name="adminEmail" type="email" required placeholder="admin@maktab.uz"/></div></div><p className="privacy-note"><span>🔐</span><span><b>Parol o‘rnatilmaydi</b><small>Email taklifida admin akkauntini o‘zi faollashtiradi va parolini o‘zi belgilaydi.</small></span></p><button className="primary invite-submit" disabled={busy}><School size={16}/>{busy?"Bazaga yozilmoqda…":"Maktabni ulash va admin taklif qilish"}<UserPlus size={15}/></button>{notice&&<div className="notice success" role="status">{notice}</div>}{error&&<div className="notice error" role="alert">{error}</div>}</form>
}
